name: Build Admin

on:
  push:
    branches: ["main", "dev"]
    paths:
      - apps/admin/**
      - packages/**
      - .github/workflows/**
  pull_request:
    branches: ["main", "dev"]
    paths:
      - apps/admin/**
      - packages/**
      - .github/workflows/**

jobs:
  # build:
  # name: Build Admin
  #   Setup build configuration

  trigger-scan:
    uses: ./.github/workflows/sonarqube-scan.yml
    with:
      project-key: mono-admin
      project-base-dir: ./apps/admin
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ADMIN }}
