name: Build Admin

on:
  push:
    branches: ["main", "dev"]
    paths:
      - apps/admin/**
      - packages/**
      - .github/workflows/**
  pull_request:
    branches: ["main", "dev"]
    paths:
      - apps/admin/**
      - packages/**
      - .github/workflows/**

jobs:
  build:
    name: Check Code Quality
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Scan the code quality
      - name: SonarQube Scan
        id: sonar
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ADMIN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=mono-admin
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN_ADMIN }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ADMIN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
