name: Build Client

on:
  push:
    branches: ["main", "dev"]
    paths:
      - apps/client/**
      - packages/**
      - .github/workflows/**
  pull_request:
    branches: ["main", "dev"]
    paths:
      - apps/client/**
      - packages/**
      - .github/workflows/**

jobs:
  # build:
  # name: Build Client
  #   Setup build configuration

  trigger-scan:
    uses: ./.github/workflows/sonarqube-scan.yml
    with:
      project-key: mono-client
      project-base-dir: ./apps/client
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
