name: Build Client

on:
  push:
    branches: ["main", "dev"]
    paths:
      - apps/client/**
      - packages/**
      - .github/workflows/**
  pull_request:
    branches: ["main", "dev"]
    paths:
      - apps/client/**
      - packages/**
      - .github/workflows/**

jobs:
  build:
    name: Build Client
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install unzip
        run: sudo apt-get install -y unzip
      - name: Setup SonarScanner
        id: sonar
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=mono-client
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN_CLIENT }}
      # - name: Install Node.js
      #   if: steps.sonar.outcome == 'success'
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.x
      #     cache: "npm"
      #     cache-dependency-path: subdir/package-lock.json
      # - run: npm i
      #   if: steps.sonar.outcome == 'success'
      # - run: npm run build
      #   if: steps.sonar.outcome == 'success'
