name: Build Client

on:
  push:
    branches: ["main", "dev"]
    paths:
      - apps/client/**
      - packages/**
      - .github/workflows/**
  pull_request:
    branches: ["main", "dev"]
    paths:
      - apps/client/**
      - packages/**
      - .github/workflows/**

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build Client
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        working-directory: ./apps/client

      # - name: Build client
      #   run: npm run build
      #   working-directory: ./apps/client

  trigger-scan:
    needs: build
    runs-on: self-hosted
    if: success()
    steps:
      - name: Trigger Scan Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'client_scan.yml',
              ref: context.ref
            })
